[package]
name = "f-i6-audio-controller"
version = "0.1.0"
authors = ["b.wisman <b.wisman155@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.49.0"

[dependencies]
cpal = "0.8.2"
libc = "0.2.53"
